# Site settings
title: Niamh Lawlor
email: nileahtobhair@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Niamh Lawlor (nileahtobhair) portfolio site.
  Software Developer
baseurl: "" 
url: "https://niamhlawlor.com" 
paginate: 10
twitter_username: nileahtobhair
github_username:  nileahtobhair
collections:
  projects:
    output: true

# Build settings
markdown: kramdown
plugins: [jekyll-paginate]

