# Site settings
title: Niamh Lawlor
email: nileahtobhair@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Niamh Lawlor (nileahtobhair) portfolio site.
  Software Developer , Dublin , Ireland
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://niamhlawlor.com" # the base hostname & protocol for your site
paginate: 10
twitter_username: nileahtobhair
github_username:  nileahtobhair
collections:
  projects:
    output: true

# Build settings
markdown: kramdown

